Repository skipperbent/simple-php-router, pull requests merged in 2021-03, with the labels that each got.

#498 [FEATURE] Added support for class hinting on routes as requested by #491
  .idea/workspace.xml
  README.md
  src/Pecee/SimpleRouter/Route/IRoute.php
  src/Pecee/SimpleRouter/Route/Route.php
  src/Pecee/SimpleRouter/Route/RouteController.php
  src/Pecee/SimpleRouter/Route/RouteResource.php
  src/Pecee/SimpleRouter/SimpleRouter.php
  tests/Pecee/SimpleRouter/RouterRouteTest.php
  tests/Pecee/SimpleRouter/RouterUrlTest.php
Labels: feature

#499 [BUGFIX] Fixed issue with child groups not loading when using partialGroups (issue: #456)
  .idea/workspace.xml
  src/Pecee/SimpleRouter/Route/RouteGroup.php
  tests/Pecee/SimpleRouter/RouterPartialGroupTest.php
  tests/TestRouter.php
Labels: bug

#513 [!!!][FEATURE] Removed php-di as suggested by #477
  .gitignore
  README.md
  composer.json
  src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php
  src/Pecee/SimpleRouter/ClassLoader/IClassLoader.php
  src/Pecee/SimpleRouter/Handlers/EventHandler.php
  src/Pecee/SimpleRouter/Route/Route.php
  src/Pecee/SimpleRouter/Router.php
  src/Pecee/SimpleRouter/SimpleRouter.php
  tests/Pecee/SimpleRouter/ClassLoaderTest.php
  tests/Pecee/SimpleRouter/DependencyInjectionTest.php
  tests/Pecee/SimpleRouter/Dummy/ClassLoader/CustomClassLoader.php
  tests/Pecee/SimpleRouter/Dummy/DummyController.php
Labels: enhancement, feature

#507 [FEATURE] Default-namespace optimisations #446
  src/Pecee/Http/Input/InputHandler.php
  src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php
  src/Pecee/SimpleRouter/Exceptions/ClassNotFoundHttpException.php
  src/Pecee/SimpleRouter/Route/Route.php
  src/Pecee/SimpleRouter/SimpleRouter.php
  tests/Pecee/SimpleRouter/RouterUrlTest.php
Labels: enhancement

#508 [BUGFIX] BootManager findRoute not working.
  README.md
  src/Pecee/SimpleRouter/Router.php
  tests/Pecee/SimpleRouter/BootManagerTest.php
  tests/Pecee/SimpleRouter/Dummy/Managers/FindUrlBootManager.php
  tests/Pecee/SimpleRouter/Dummy/Managers/TestBootManager.php
  tests/Pecee/SimpleRouter/EventHandlerTest.php
Labels: bug

#509 [BUGFIX] Issue #439: Fixed multiple request-type on same routes.
  src/Pecee/SimpleRouter/Router.php
  tests/Pecee/SimpleRouter/RouterRouteTest.php
Labels: bug

#510 [FEATURE] Option to disable multi-route-rendering #452
  README.md
  src/Pecee/SimpleRouter/Router.php
  src/Pecee/SimpleRouter/SimpleRouter.php
  tests/Pecee/SimpleRouter/RouterUrlTest.php
Labels: feature

#514 [FEATURE] Add support for mixed value types in InputItem as requested by #438
  src/Pecee/Http/Input/IInputItem.php
  src/Pecee/Http/Input/InputItem.php
Labels: feature

#512 GitHub actions
  .github/workflows/ci.yml
  composer.json
  phpunit.xml
Labels: feature

#517 PHPUnit file tests
  tests/Pecee/SimpleRouter/InputHandlerTest.php
Labels: enhancement

#521 [BUGFIX] Fixed group not matching domain with no parameters (issue: #468)
  src/Pecee/SimpleRouter/Route/RouteGroup.php
  tests/Pecee/SimpleRouter/RouterRouteTest.php
Labels: bug

#523 [FEATURE] Added Request::isPostBack helper method
  README.md
  src/Pecee/Http/Request.php
Labels: feature

#524 [CLEANUP] Cleaned up code
  src/Pecee/Http/Request.php
  src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php
  src/Pecee/SimpleRouter/Event/EventArgument.php
  src/Pecee/SimpleRouter/Exceptions/ClassNotFoundHttpException.php
  src/Pecee/SimpleRouter/Route/IGroupRoute.php
  src/Pecee/SimpleRouter/Route/ILoadableRoute.php
  src/Pecee/SimpleRouter/Route/IRoute.php
  src/Pecee/SimpleRouter/Route/LoadableRoute.php
  src/Pecee/SimpleRouter/Route/Route.php
  src/Pecee/SimpleRouter/Route/RouteController.php
  src/Pecee/SimpleRouter/Route/RouteGroup.php
  src/Pecee/SimpleRouter/Route/RoutePartialGroup.php
  src/Pecee/SimpleRouter/Route/RouteResource.php
  src/Pecee/SimpleRouter/Route/RouteUrl.php
  src/Pecee/SimpleRouter/Router.php
  src/Pecee/SimpleRouter/SimpleRouter.php
Labels: enhancement

#527 [FEATURE] Added support for parameters in group prefix.
  README.md
  src/Pecee/SimpleRouter/Route/Route.php
  src/Pecee/SimpleRouter/Route/RouteGroup.php
  src/Pecee/SimpleRouter/Route/RoutePartialGroup.php
  tests/Pecee/SimpleRouter/RouterUrlTest.php
Labels: feature

#526 Version 4.3.1.0-test
  README.md
  src/Pecee/Http/Exceptions/MalformedUrlException.php
  src/Pecee/Http/Input/InputHandler.php
  src/Pecee/Http/Input/InputItem.php
  src/Pecee/Http/Middleware/BaseCsrfVerifier.php
  src/Pecee/Http/Middleware/Exceptions/TokenMismatchException.php
  src/Pecee/Http/Request.php
  src/Pecee/Http/Response.php
  src/Pecee/Http/Security/CookieTokenProvider.php
  src/Pecee/Http/Security/Exceptions/SecurityException.php
  src/Pecee/Http/Url.php
  src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php
  src/Pecee/SimpleRouter/ClassLoader/IClassLoader.php
  src/Pecee/SimpleRouter/Event/EventArgument.php
  src/Pecee/SimpleRouter/Exceptions/HttpException.php
  src/Pecee/SimpleRouter/Handlers/CallbackExceptionHandler.php
  src/Pecee/SimpleRouter/Handlers/DebugEventHandler.php
  src/Pecee/SimpleRouter/Handlers/EventHandler.php
  src/Pecee/SimpleRouter/Handlers/IExceptionHandler.php
  src/Pecee/SimpleRouter/Route/LoadableRoute.php
  src/Pecee/SimpleRouter/Route/Route.php
  src/Pecee/SimpleRouter/Route/RouteController.php
  src/Pecee/SimpleRouter/Route/RouteGroup.php
  src/Pecee/SimpleRouter/Route/RoutePartialGroup.php
  src/Pecee/SimpleRouter/Route/RouteResource.php
  src/Pecee/SimpleRouter/Router.php
  src/Pecee/SimpleRouter/SimpleRouter.php
  tests/Pecee/SimpleRouter/Dummy/ClassLoader/CustomClassLoader.php
  tests/Pecee/SimpleRouter/InputHandlerTest.php
  tests/Pecee/SimpleRouter/RouterPartialGroupTest.php
  tests/Pecee/SimpleRouter/RouterUrlTest.php
Labels: bug, feature

#530 [FEATURE] Added include property to BaseCsrfVerifier + unit tests.
  src/Pecee/Http/Middleware/BaseCsrfVerifier.php
  tests/Pecee/SimpleRouter/CsrfVerifierTest.php
  tests/Pecee/SimpleRouter/Dummy/CsrfVerifier/DummyCsrfVerifier.php
Labels: feature
